### PR TITLE
Allow variables to be referenced using dot syntax in parameter

### PR DESCRIPTION
**Pull request by coatesap**
This change allows a property of an object to be used in the directive's parameter, eg:

<div class="item-instance" ng-repeat-n="item.qty">

It uses Angular's $parse function to safely resolve the string in the current scope.

### CODE REVIEW

**Comment by coatesap** [comment]
@connorbode Hi, is there any news on whether this will be merged?

**Comment by RQuadling** [comment]
Please can PR be merged. Very useful feature addition.

**Comment by connorbode** [comment]
@coatesap Sorry, I missed the original notification.  

Two things

1. Because you used 4 space tabs instead of 2 space tabs, the change overwrites the entire file.  Can you resubmit modifying only the necessary lines?
2. Can you write some simple unit tests to cover the functionality you've written?

**Comment by connorbode** [comment]
@coatesap still waiting on a comment!

**Comment by coatesap** [comment]
@connorbode Sorry I haven't had chance to look at this since the original pull request...

1. Yes, originally my IDE autoformatted the file with 4 spaces, but I corrected this in a later commit. If you look at the consolidated diff on Github, it should just show the few lines that were added.
2. If I'm honest, I may not get time for a while to write any tests for this functionality. However, any tests you currently have should ensure that existing functionality is preserved, and for the additional functionality, this uses Angular's $parse pretty directly, which is already well tested in it's own right. I will add tests for this to my list of things to do though.

**Pull request closed without merging**
